name: news_and_weathers_hub
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.3

dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.2.0
  cupertino_icons: ^1.0.9
  dio: ^5.10.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.1
  flutter_riverpod: ^3.3.2
  geolocator: ^14.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.3
  mocktail: ^1.0.5
  package_info_plus: ^10.2.0
  share_plus: ^13.2.0
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - .env
